set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_SYSTEM_PROCESSOR x86)
set (CMAKE_CROSSCOMPILING 1)

set (CMAKE_C_COMPILER wcl386)
set (CMAKE_CXX_COMPILER wcl386)
set (CMAKE_ASM_COMPILER wasm)
set (CMAKE_ASM_COMPILER_ID "WATCOM")
set (CMAKE_AR wlib)

add_definitions (-D__i386__)

set (CMAKE_C_FLAGS "-bt=dos -l=dos4g -s -3s -k128k -i=/home/kicsyromy/workspace/watcom-test/3rdparty/allegro/include ${CMAKE_C_FLAGS}")
set (CMAKE_CXX_FLAGS "-bt=dos -l=dos4g -s -3s -k128k ${CMAKE_CXX_FLAGS}")

set (CMAKE_C_FLAGS_RELEASE "-ox ${CMAKE_C_FLAGS_RELEASE}")
set (CMAKE_C_FLAGS_MINSIZEREL "-os ${CMAKE_C_FLAGS_MINSIZEREL}")
set (CMAKE_C_FLAGS_RELWITHDEBINFO "-ox -et ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
set (CMAKE_C_FLAGS_DEBUG "-od ${CMAKE_C_FLAGS_DEBUG}")
set (CMAKE_CXX_FLAGS_RELEASE "-ox ${CMAKE_CX_FLAGS_RELEASE}")
set (CMAKE_CXX_FLAGS_MINSIZEREL "-os ${CMAKE_CX_FLAGS_MINSIZEREL}")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-ox -et ${CMAKE_CX_FLAGS_RELWITHDEBINFO}")
set (CMAKE_CXX_FLAGS_DEBUG "-od ${CMAKE_CX_FLAGS_DEBUG}")

set (CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <SOURCE> -c <FLAGS> -fo=<OBJECT>")
set (CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> <SOURCE> -c <FLAGS> -fo=<OBJECT>")

set (CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> <OBJECTS> /home/kicsyromy/workspace/watcom-test/3rdparty/allegro/lib/alleg.lib <LINK_FLAGS> ${CMAKE_C_FLAGS} -fe=<TARGET>.exe")
set (CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_CXX_COMPILER> <OBJECTS> <LINK_FLAGS> ${CMAKE_CXX_FLAGS} -fe=<TARGET>.exe")

set (CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> <TARGET> <LINK_FLAGS> <OBJECTS>")
set (CMAKE_CXX_CREATE_STATIC_LIBRARY ${CMAKE_C_CREATE_STATIC_LIBRARY})
set (CMAKE_ASM_CREATE_STATIC_LIBRARY ${CMAKE_C_CREATE_STATIC_LIBRARY})
